apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-pos.fullname" . }}-api
  labels:
    {{- include "simple-pos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
