apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-pos.fullname" . }}-postgres
  labels:
    {{- include "simple-pos.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
