apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-pos.fullname" . }}-redis
  labels:
    {{- include "simple-pos.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: redis
      port: 6379
      targetPort: redis
