apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-pos.fullname" . }}-api-secrets
  labels:
    {{- include "simple-pos.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.api.env.jwtSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.api.env.jwtRefreshSecret | quote }}
  STRIPE_SECRET_KEY: {{ .Values.api.env.stripeSecretKey | quote }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.api.env.stripeWebhookSecret | quote }}
  STRIPE_PRICE_BASIC: {{ .Values.api.env.stripePriceBasic | quote }}
  STRIPE_PRICE_PRO: {{ .Values.api.env.stripePricePro | quote }}
  STRIPE_PRICE_ENTERPRISE: {{ .Values.api.env.stripePriceEnterprise | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-pos.fullname" . }}-postgres-secrets
  labels:
    {{- include "simple-pos.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
